### ISSUE TITLE
Missing artifact epsl:epsl-lang

### ISSUE THREAD

**Issue by lsylusiyao** [pstlab/PLATINUm#3]
Hello, I've tried to compile and run the project, but I found out that I couldn't download `epsl-lang:0.0.1` since it doesn't exist in `Maven Repository`. I searched the package manually on the [website](https://mvnrepository.com/search?q=epsl) and it shows no result. Would you mind just uploading this package into the repo? Thanks. 

PS: Here's the message given by VSCode: `Missing artifact epsl:epsl-lang:jar:0.0.1`

**Comment by viraj96** [comment]
Did you take a look at [this](https://github.com/pstlab/PLATINUm/packages/265022)?

**Comment by lsylusiyao** [comment]
Thanks you very much. It worked. Sorry I am not really familiar with Java's Maven and the `GitHub Packages` so I didn't notice that.  
BTW, it seems that this should be downloaded and installed manually by CLI so here I'll leave my command here: 

```cmd
mvn install:install-file -Dfile=PATH_TO_EPSL_JAR -DgroupId=epsl -DartifactId=epsl-lang -Dversion=0.0.1 -Dpackaging=jar
```
